### ISSUE TITLE
Without Mongoid

### ISSUE THREAD

**Issue by eikes** [fhir-crucible/fhir_dstu2_models#3]
Is it possible to use this gem without mongoid? If not, would it be difficult rebuild the models without including Mongoid mixins or stripping those out? Would they still work?

Or to phrase my question differently: Why do all models have this line ```include Mongoid::Document```?

**Comment by jawalonoski** [comment]
The latest pull request, if merged, will fix this problem.

**Comment by eikes** [comment]
That's awesome, thanks!

**Comment by jawalonoski** [comment]
Fixed with #4
